---
title: "Nine simple ways"
author: "Andrew MacDonald"
date: "March 1, 2016"
output: ioslides_presentation
---

## Nine simple ways to reuse your data:

> Nine simple ways to make it easier to (re)use your data
Ethan P White, Elita Baldridge, Zachary T. Brym, Kenneth J. Locey, Daniel J. McGlinn, Sarah R. Supp

## 1. Share your data

## 2. Provide metadata

* datapackage
* EML
* `.csvy`

etc

## 3. Provide an unprocessed form of the data

* `data-raw`
* `data` is only the beginning

## 4. Use standard data formats {.build}

* `.csv`
* Use standard table formats
* **Each row should represent a single observation
(i.e., record) and each column should represent a
single variable or type of measurement (i.e., field)**
* Avoid special characters.
* When working with dates use the YYYY-MM-DD

## 5. Use good null values

> Whichever null value you use, only use one,
use it consistently throughout the data set, and indicate
it clearly in the metadata.

## 6. Make it easy to combine your data with other
datasets

> You can make it easier to combine your data with other data sources by including contextual data that appears across similar data sources.
Two of the most common kinds of contextual data in
ecology and evolution are taxonomy and geographic
location.

`README.md` among other places

## 7. Perform basic quality control

> At its most basic, quality control can consist of a few
quick sanity checks.

`assertr`, and also the Peer Review process

## 8. Use an established repository

> For data sharing to be effective, data should be easy
to find, accessible, and stored where it will be preserved
for a long time

* [Figshare](https://figshare.com/)
* [Knowledge Network for Biocomplexity](https://knb.ecoinformatics.org/#)
* [Dryad](http://datadryad.org/)
* [Zenodo](https://zenodo.org/)


## 9. Use an established and open license

* `CC-0` is very common for data :

> The Creative Commons Zero (CC0) public domain
dedication places no restrictions on data use and is
considered by many to be one of the best ways to share
data